Customizable Item Swap Cooldown
dniym/IllegalStack pull request #83
Opened 2020-09-06 15:47 UTC by LaserSlimeHD

The default cooldown of 750ms is quite long. 500 should be more than enough to prevent the exploit. For some reason the cooldown time is displayed before the actual option in the generated config. No idea how to fix that. The old value also gets reset due to the path change. I tried to make it consistent with the rest of the config design.

Also fixed typo.

2020-09-06 17:49 UTC, dniym requested changes

2020-09-06 17:49 UTC, dniym commented on src/main/java/me/dniym/enums/Protections.java
> +    ItemSwapCooldown(59, 500, "Cooldown Time (Miliseconds)", 59, "Exploits.ItemSwap.ItemSwapCooldown", "Time the player has to wait between item swaps in miliseconds.", "", 0, false),
Could you please also add a disclaimer here explaining that if they make the cooldown too low then players may be able to lag the server?   I know it seems obvious but without it someone may just set it to 1ms then later complain the protection is not working.

2020-09-06 17:53 UTC, LaserSlimeHD commented on src/main/java/me/dniym/enums/Protections.java
> +    ItemSwapCooldown(59, 500, "Cooldown Time (Miliseconds)", 59, "Exploits.ItemSwap.ItemSwapCooldown", "Time the player has to wait between item swaps in miliseconds.", "", 0, false),
I could use ticks instead of milliseconds. At the minimum of one tick, players still shouldn't be able to lag other players, because that's basically the speed that a vanilla players swaps when holding down the f-key, as far as I know.

2020-09-06 18:38 UTC, LaserSlimeHD commented on src/main/java/me/dniym/enums/Protections.java
> +    ItemSwapCooldown(59, 500, "Cooldown Time (Miliseconds)", 59, "Exploits.ItemSwap.ItemSwapCooldown", "Time the player has to wait between item swaps in miliseconds.", "", 0, false),
I found a strange bug: If you have an old config and update to the this new version, it will set the cooldown to 0 after stopping the server, which completely disables the protections. No idea how to fix this.

2020-09-09 19:50 UTC, dniym commented on src/main/java/me/dniym/enums/Protections.java
> +    ItemSwapCooldown(59, 500, "Cooldown Time (Miliseconds)", 59, "Exploits.ItemSwap.ItemSwapCooldown", "Time the player has to wait between item swaps in miliseconds.", "", 0, false),
how old a config?  like from a super old version? or when it is first enabled the next reboot it goes to 0?

2020-09-10 16:29 UTC, LaserSlimeHD commented on src/main/java/me/dniym/enums/Protections.java
> +    ItemSwapCooldown(59, 500, "Cooldown Time (Miliseconds)", 59, "Exploits.ItemSwap.ItemSwapCooldown", "Time the player has to wait between item swaps in miliseconds.", "", 0, false),
I mean a config generated before this.

2021-01-20 14:29 UTC, DontNeedAName commented on src/main/java/me/dniym/enums/Protections.java
> +    ItemSwapCooldown(59, 500, "Cooldown Time (Miliseconds)", 59, "Exploits.ItemSwap.ItemSwapCooldown", "Time the player has to wait between item swaps in miliseconds.", "", 0, false),
So I now added the "disclaimer" however my local repository is kinda broken and git will not let me push the upstream changes to my repository. I also have dependency errors so I can't test if the config issue still occurs.

2023-06-14 21:21 UTC, dniym commented on src/main/java/me/dniym/enums/Protections.java
> +    ItemSwapCooldown(59, 500, "Cooldown Time (Miliseconds)", 59, "Exploits.ItemSwap.ItemSwapCooldown", "Time the player has to wait between item swaps in miliseconds.", "", 0, false),
I know this is old but im closing some old PR's if you would like to re-add this please do it via the latest version.

2023-06-14 21:21 UTC, closed without merging